=== Margauxluyten/TheZoo/src/main/java/families.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:fam="fam" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="fam">
    <xs:element name="families" type="fam:familiesType"/>
    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element type="xs:string" name="streetname"/>
            <xs:element type="xs:string" name="housenumber"/>
            <xs:element  name="postcode">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1000"/>
                        <xs:maxInclusive value="9999"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="city"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="memberType">
        <xs:sequence>
            <xs:element name="firstname">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="person 1"/>
                        <xs:enumeration value="person 2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="lastname">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="persons 1 last name"/>
                        <xs:enumeration value="person 2 last name"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="gender" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="gender" use="optional"/>
    </xs:complexType>
    <xs:complexType name="membersType">
        <xs:sequence>
            <xs:element type="fam:memberType" name="member" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="nameType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="species"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="petType">
        <xs:sequence>
            <xs:element type="fam:nameType" name="name"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="petsType">
        <xs:sequence>
            <xs:element type="fam:petType" name="pet"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="familyType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="fam:addressType" name="address"/>
            <xs:element type="fam:membersType" name="members"/>
            <xs:element type="fam:petsType" name="pets"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="familiesType">
        <xs:sequence>
            <xs:element type="fam:familyType" name="family"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Margauxluyten/TheZoo/src/main/java/families.xml
<?xml version="1.0"?>
<families xmlns="fam" xmlns:x="http://www.w3.org/2001/XMLSchema-instance" x:schemaLocation="fam families.xsd" >
    <family>
        <name>Leduc</name>
        <address>
            <streetname>MyStreet</streetname>
            <housenumber>8</housenumber>
            <postcode>9999</postcode>
            <city>SomeCity</city>
        </address>
        <members>
            <member gender="MALE">
                <firstname>person 1</firstname>
                <lastname>persons 1 last name</lastname>
            </member>
            <member gender="FEMALE">
                <firstname>person 2</firstname>
                <lastname>person 2 last name</lastname>
                <gender>FEMALE</gender>
            </member>
        </members>
        <pets>
            <pet>
                <name species="DOG">Jef</name>
            </pet>
        </pets>
    </family>
</families>
