=== Margauxluyten/TheZoo/src/main/family.dtd
<!ELEMENT family (myfamilyMembers|marriedFamilyMembers)*>
        <!ELEMENT myfamilyMembers (grandParents|parents|parentsSiblings|siblings|wife)*>
        <!ELEMENT grandParents (member)*>
        <!ELEMENT member (#PCDATA)>
        <!ATTLIST member
                name CDATA #REQUIRED>
        <!ELEMENT parents (member)*>
        <!ELEMENT parentsSiblings (member)*>
        <!ELEMENT siblings (member)*>
        <!ELEMENT wife (member)*>
        <!ELEMENT marriedFamilyMembers (familyOfWife)*>
        <!ELEMENT familyOfWife (#PCDATA)>

=== Margauxluyten/TheZoo/src/main/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "C:\Users\tlubb59\Documents\My RD projects\TheZoo\src\main\family.dtd">
<family>
    <myfamilyMembers>
        <grandParents>
            <member name="Filip">Pops</member>
            <member name="etc">Nanny</member>
            <member name = "etc">Other pop</member>
            <member name = "etc">Other nan</member>
        </grandParents>
        <parents>
            <member name ="etc">Mom</member>
            <member name = "etc">Dad</member>
        </parents>
        <parentsSiblings>
            <member name = "etc">Uncle</member>
            <member name = "etc">Other uncle</member>
            <member name = "etc">Aunt</member>
            <member name = "etc">Other Aunt</member>
        </parentsSiblings>
        <siblings>
            <member name = "etc">Sister</member>
            <member name = "etc">Other sister</member>
        </siblings>
        <wife>
            <member name ="etc">Wiederhalf</member>
        </wife>
    </myfamilyMembers>

    <marriedFamilyMembers>
        <familyOfWife>

        </familyOfWife>
    </marriedFamilyMembers>
</family>
